[package]
name = "swaptop"
version = "0.1.0"
edition = "2024"
authors = ["Luis Otavio <luotasss@gmail.com>"]

[dependencies]
procfs = "0.17.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
thiserror = "2.0.12"
crossterm = "0.28.1"
color-eyre = "0.6.3"