name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            flags: "--features linux"
          - target: x86_64-pc-windows-gnu
            flags: "--features windows_support"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and release Rust binary
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_COMMAND_FLAGS: ${{ matrix.flags }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: "tar.gz zip"
          MINIFY: "true"
          BIN_NAME: "swaptop"
          RELEASE_NAME: "Release ${{ github.ref_name }}"
          RELEASE_BODY: "Automated release for ${{ github.ref_name }}"
          EXTRA_FILES: "README.md LICENSE"
