name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "autobuild-${{ github.run_number }}"
          release_name: "Auto Release #${{ github.run_number }}"
          body: |
            Automated build from `${{ github.ref }}`
          draft: false
          prerelease: false

  release:
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            features: linux
          - target: x86_64-pc-windows-gnu
            features: windows_support
            toolchain: nightly

    steps:
      - uses: actions/checkout@v4

      - name: Build and upload Rust binary
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          UPLOAD_MODE: release
          RUSTTARGET: ${{ matrix.target }}
          FEATURES: ${{ matrix.features }}
          TOOLCHAIN_VERSION: ${{ matrix.toolchain || 'stable' }}
          ARCHIVE_TYPES: "zip tar.gz"
          EXTRA_FILES: "README.md LICENSE"
