name: Release

on:
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Linux build: use Musl + linux feature
          - target: x86_64-unknown-linux-musl
            features: linux


          # Windows build: use GNU + windows_support feature + nightly toolchain
          - target: x86_64-pc-windows-gnu
            features: windows_support
            toolchain: nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and release Rust binary
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: "zip tar.gz"
          MINIFY: "true"
          EXTRA_FILES: "README.md LICENSE"
          FEATURES: ${{ matrix.features }}
          TOOLCHAIN_VERSION: ${{ matrix.toolchain || 'stable' }}
