name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="autobuild-$(date +%s)"
          gh release create "$tag" \
            --title "Auto Release $tag" \
            --notes "Automated release from push on ${{ github.ref_name }}" \
            --latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}

  release:
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            features: linux
          - target: x86_64-pc-windows-gnu
            features: windows_support
            toolchain: nightly

    steps:
      - uses: actions/checkout@v4
      - name: Build and upload Rust binary
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          UPLOAD_MODE: release
          RUSTTARGET: ${{ matrix.target }}
          FEATURES: ${{ matrix.features }}
          TOOLCHAIN_VERSION: ${{ matrix.toolchain || 'stable' }}
          ARCHIVE_TYPES: "zip tar.gz"
          EXTRA_FILES: "README.md LICENSE"

